### PR TITLE
Setup rails project

### LINKED ISSUE #13: Set up a new Rails project
The development team are aligned that Ruby on Rails is likely the best candidate for backend framework for this project. It is the framework we collectively know the best and it has a feature set that removes/lessens some of our headaches.

At this stage we don't quite know what we need, but a database is always a good bet!

## Acceptance criteria

- [x] Install the latest version of Ruby on Rails into this project directory

## Notes and links

We will be setting up RSpec as part of another ticket, to make life easier I would suggest running `rails new` with `-T` to mean no tests are added using the default test runner.

Also, to make things easier for running the database locally, I would suggest running `rails new` with  `-d=postgresql` this will tell Rails to use postgresql over sqlite

### PR DESCRIPTION
**Pull request by francosta**
Closes #13.
Created rails application in the current project directory.

### CODE REVIEW

**Comment by mathewtrivett** [comment]
@francosta it would probably be worthwhile bumping up your version of Ruby and of Rails to the latest versions? It looks like this is Ruby 2.6 and Rails 5. Not sure what you think @tosbourn ?

**Comment by francosta** [comment]
I think this makes sense @mathewtrivett. The last version I've seen available for Ruby  is v2.7.2 and for Rails is v6.0.3.4. Should we use these?

**Comment by tosbourn** [comment]
> I think this makes sense @mathewtrivett. The last version I've seen available for Ruby is v2.7.2 and for Rails is v6.0.3.4. Should we use these?

Yup, I think we should use latest-and-greatest 👍

**Review by tosbourn — CHANGES_REQUESTED** [review]
Looks fab! As @mathewtrivett pointed out, we may as well start as we mean to go on with versions and use the latest versions available. Once that is done this looks good to go!

**Pull request closed without merging**
