### PR TITLE
Technical decisions

### PR DESCRIPTION
**Pull request by francosta**
Added docs on technical decisions for wicked gem and  tfl api

### CODE REVIEW

**Review by tosbourn — APPROVED** [review]
👍

**Comment by mathewtrivett** [comment]
Hi Fran, this looks good but like it may not rebase / merge correctly for some reason? @tosbourn not sure if you can help with a fix here or shall we just do a merge commit on this one?

**Comment by mathewtrivett** [comment]
@francosta did you rebase from main before pushing this commit?

**Comment by francosta** [comment]
No, not sure what happened here - don't know why it's showing commits since the start 🤔 
Should I create a new branch from main and add the 2 files and create a new pull request?

**Comment by mathewtrivett** [comment]
First try:

- Pull the latest changes from main
- Switch to this `technical-decisions` branch and run `git rebase main`
- Then push and see if that resolves it.

I think before he leaves us 😢 it would be great to get a solid git rebase lesson from @tosbourn if we can?

If not, then your option to create a new branch would work too.

**Comment by mathewtrivett** [comment]
@francosta the other option is here is that you include the ADR for wicked wizard in your PR for #40 and then we can pick up the ADR for TfL in another related ticket. That way all of the content is connected to the code if someone were to track back the commits.

**Comment by tosbourn** [comment]
@francosta can we rebase main into this and get it merged?

**Comment by francosta** [comment]
On it now @tosbourn

**Pull request merged**
